spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      # 这是 Spring Batch 自带的 MySQL 脚本文件
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql
      mode: always